// apps/nativescript-query-vue/src/components/Post.vue
<script lang="ts" setup>
import { ref, computed } from 'nativescript-vue';
import { useQuery } from '@tanstack/vue-query';
import { apiDetailUrl, Post } from '@org/state';

const props = defineProps<{
  post: Post;
}>();

const fetcher = async (id: number): Promise<Post> =>
  await fetch(apiDetailUrl(id)).then((response) => response.json());

const post = computed(() => props.post);
const postId = computed(() => post?.value?.id);

const { isFetching, error, status } = useQuery({
  queryKey: ['post', post.value.id],
  queryFn: () => fetcher(post.value.id),
});
</script>

<template>
  <Page>
    <ActionBar :title="'Post ' + postId"> </ActionBar>
    <GridLayout rows="auto,auto,*,auto" class="p-6">
      <Label
        v-if="status === 'pending'"
        class="text-black/50 italic text-lg m-2"
        >Loading...</Label
      >
      <Label
        v-if="status === 'error'"
        class="text-red-500 font-bold text-lg m-2"
        >Error: {{ error?.message }}</Label
      >

      <Label row="1" class="text-black text-2xl leading-3" textWrap="true">{{
        post.title
      }}</Label>
      <GridLayout row="2" class="mt-6">
        <Label
          class="text-black/75 text-lg leading-3 align-top"
          textWrap="true"
          >{{ post.body }}</Label
        >
      </GridLayout>

      <Label v-if="isFetching" row="3" class="text-black/50 italic m-2"
        >Background Updating...</Label
      >
    </GridLayout>
  </Page>
</template>

// apps/nativescript-query-ng/src/features/post/components/post.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  inject,
  signal,
} from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import {
  injectQuery,
  injectQueryClient,
} from '@tanstack/angular-query-experimental';
import { fromEvent, lastValueFrom, map, takeUntil } from 'rxjs';
import { PostsService } from '../../../core/services/posts.service';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'post',
  templateUrl: './post.component.html',
})
export class PostComponent {
  #postsService = inject(PostsService);
  #activeRoute = inject(ActivatedRoute);

  postId = signal(0);

  postQuery = injectQuery(() => ({
    enabled: this.postId() > 0,
    queryKey: ['post', this.postId()],
    queryFn: async (context) => {
      // Cancels the request when component is destroyed before the request finishes
      const abort$ = fromEvent(context.signal, 'abort');
      return lastValueFrom(
        this.#postsService.postById$(this.postId()).pipe(
          takeUntil(abort$),
          map((data) => {
            // cleanse new lines to allow text to wrap naturally
            return {
              ...data,
              body: data.body.replace(/\n/gi, ''),
            };
          })
        )
      );
    },
  }));

  queryClient = injectQueryClient();

  constructor() {
    this.#activeRoute.params.pipe(takeUntilDestroyed()).subscribe((params) => {
      this.postId.set(params.id);
    });
  }
}

<ActionBar [title]="'Post ' + postId()"> </ActionBar>
<GridLayout rows="auto,auto,*,auto" class="p-6">
  @if (postQuery.status() === 'pending') {
  <Label class="text-black italic text-lg m-2">Loading...</Label>
  } @else if (postQuery.status() === 'error') {
  <Label class="text-red-500 font-bold text-lg m-2"
    >Error: {{ postQuery.error()?.message }}</Label
  >
  } @if (postQuery.data(); as post) {
  <Label row="1" class="text-black text-2xl leading-3" textWrap="true">{{
    post.title
  }}</Label>
  <GridLayout row="2" class="mt-6">
    <Label class="text-black/75 text-lg leading-3 align-top" textWrap="true">{{
      post.body
    }}</Label>
  </GridLayout>
  @if (postQuery.isFetching()) {

  <Label row="3" class="text-black/50 italic m-2">Background Updating...</Label>
  } }
</GridLayout>
