// apps/nativescript-query-vue/src/components/Posts.vue
<script lang="ts" setup>
import { EventData, ItemEventData, ListView, Page } from '@nativescript/core';
import { apiUrl, Post, stateDidVisit, stateVisitedLinks } from '@org/state';
import { computed, $navigateTo } from 'nativescript-vue';
import { useQuery } from '@tanstack/vue-query';
import PostDetail from './Post.vue';

const fetcher = async (): Promise<Post[]> =>
  await fetch(apiUrl).then((response) => response.json());

const { data, refetch } = useQuery({
  queryKey: ['posts'],
  queryFn: fetcher,
});

const items = computed(() => {
  console.log('posts updated!', data)
  return (data.value || []).map(stateDidVisit);
});

function loaded(args: EventData) {
  const page = args.object as Page;
  if (__IOS__) {
    const navigationController: UINavigationController =
      page.frame.ios.controller;
    navigationController.navigationBar.prefersLargeTitles = true;
  }
}

function navigateToDetails(args: ItemEventData) {
  const post = items.value[args.index];
  stateVisitedLinks.set(post.id, true);
  $navigateTo(PostDetail, {
    props: {
      post: {
        ...post,
        body: post.body.replace(/\n/g, ''),
      },
    },
  });
}

function navigatedTo() {
  if (stateVisitedLinks.size) {
    // only when links have been visited
    // for demonstration purposes, allows list to highlight visited posts green
    refetch();
  }
}
</script>

<template>
  <Frame>
    <Page @loaded="loaded" @navigatedTo="navigatedTo">
      <ActionBar title="Tanstack Query"> </ActionBar>

      <GridLayout>
        <ListView :items="items" @itemTap="navigateToDetails">
          <template #default="{ item }">
            <StackLayout class="p-4">
              <Label
                class="text-lg"
                :class="{
                  'text-gray-500': !item.visited,
                  'text-green-500': item.visited,
                }"
                :text="'- ' + item.title"
              />
            </StackLayout>
          </template>
        </ListView>
      </GridLayout>
    </Page>
  </Frame>
</template>

// apps/nativescript-query-ng/src/features/posts/components/posts.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { ItemEventData, Page, Utils } from '@nativescript/core';
import { RouterExtensions } from '@nativescript/angular';
import {
  injectQuery,
  injectQueryClient,
} from '@tanstack/angular-query-experimental';
import { lastValueFrom, map } from 'rxjs';
import { PostsService } from '../../../core/services/posts.service';
import { stateDidVisit, stateVisitedLinks } from '@org/state';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'posts',
  templateUrl: './posts.component.html',
})
export class PostsComponent {
  #postsService = inject(PostsService);
  #router = inject(RouterExtensions);
  #page = inject(Page);

  postsQuery = injectQuery(() => ({
    queryKey: ['posts'],
    queryFn: () =>
      lastValueFrom(
        this.#postsService.allPosts$().pipe(
          map((data) => {
            return data.map(stateDidVisit);
          })
        )
      ),
  }));

  queryClient = injectQueryClient();

  constructor() {
    this.#page.on('loaded', () => {
      if (__IOS__) {
        const navigationController: UINavigationController =
          this.#page.frame.ios.controller;
        navigationController.navigationBar.prefersLargeTitles = true;
      }
    });

    this.#page.on('navigatedTo', () => {
      if (stateVisitedLinks.size) {
        // only when links have been visited
        // for demonstration purposes, allows list to highlight visited posts green
        this.postsQuery.refetch();
      }
    });
  }

  viewDetail(args: ItemEventData) {
    const post = this.postsQuery.data()[args.index];
    stateVisitedLinks.set(post.id, true);
    this.#router.navigate(['/post', post.id]);
  }
}

<ActionBar title="Tanstack Query"> </ActionBar>
<GridLayout>
  <ListView [items]="postsQuery.data()" (itemTap)="viewDetail($event)">
    <ng-template let-post="item">
      <StackLayout class="p-4">
        <Label
          class="text-lg"
          [ngClass]="{
            'text-gray-500': !post.visited,
            'text-green-500': post.visited
          }"
          >- {{ post.title }}</Label
        >
      </StackLayout>
    </ng-template>
  </ListView>
</GridLayout>
